### ISSUE TITLE
two-level hanging node is not treated as expected

### ISSUE THREAD

**Issue by dohyun-cse** [Terenceyuyue/mVEM#1] opened 2021-04-21 12:05 UTC
Hi!
I'm Dohyun, a postdoc working on staggered DG methods which also consider polygonal mesh.
I found [this arxiv manuscript](https://arxiv.org/pdf/2101.03456.pdf) and tried it myself.

I found that the code `PolyMeshRefine` contains two bugs
1) violate the one-hanging-node rule
2) non-unique node

The bug is reproducible by the following code

```MATLAB
% load sample mesh
load meshdata1.mat
% for consistent result
rng(0);
% display option
opt_mesh = struct('facecolor','none');
opt_mark = struct('facecolor','r');

toBeMarked = {[7], [9, 19, 20], [36]};
for i = 1 : 3
    marked = toBeMarked{i};
    % display current mesh and marked elements with node numbering
    figure;
    subplot(1,3,1);
    showmesh(node, elem,opt_mesh);
    hold on;
    showmesh(node, elem(marked),opt_mark);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    axis off

    % refine
    [node, elem] = PolyMeshRefine(node, elem, marked);

    % display refined mesh with element numbering
    subplot(1,3,2);
    showmesh(node, elem, opt_mesh);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    axis off;

    % display refined mesh with node numbering
    subplot(1,3,3);
    showmesh(node, elem, opt_mesh);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    text(node(:,1), node(:,2), num2str((1:size(node,1)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on');
    axis off;
    drawnow;
end
```

![image](https://user-images.githubusercontent.com/17425440/115549888-29a73800-a2e4-11eb-83cc-01952012f642.png)
click the above figure for clear view.

I found that this bug can be made if the following holds:
1. E1 is marked and a neighboring element E2 is not marked.
2. E1 is divided into e1, e2, ..., en where e1, e2 are neighbor of E2.
3. e1, e2, E2 are marked

As e1, e2 are further refined, E2 should contain hanging nodes created from e1 and e2.
However, the hanging nodes from e1 and e2 are omitted from the refined polygons from E2.

I think the omitted nodes are the source of bug.
As there is omitted nodes, there could be repeated nodes (omitted node from one side will be duplicated)
and the detection of a midpoint fails.

This bug can be fixed by checking whether a neighboring element is further refined or not.

**Comment by Terenceyuyue** [comment] 2021-04-21 13:19
Thank you for pointing out the bugs. 

  The updated version will be given later. 



----- 原始邮件 -----
发件人: "Dohyun Kim" ***@***.***>
收件人: "Terenceyuyue/mVEM" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期三, 2021年 4 月 21日 下午 8:06:14
主题: [Terenceyuyue/mVEM] two-level hanging node is not treated as expected (#1)

Hi!
I'm Dohyun, a postdoc working on staggered DG methods which also consider polygonal mesh.
I found [this arxiv manuscript](https://arxiv.org/pdf/2101.03456.pdf) and tried it myself.

I found that the code `PolyMeshRefine` contains two bugs
1) violate the one-hanging-node rule
2) non-unique node

The bug is reproducible by the following code

```MATLAB
% load sample mesh
load meshdata1.mat
% for consistent result
rng(0);
% display option
opt_mesh = struct('facecolor','none');
opt_mark = struct('facecolor','r');

toBeMarked = {[7], [9, 19, 20], [36]};
for i = 1 : 3
    marked = toBeMarked{i};
    % display current mesh and marked elements with node numbering
    figure;
    subplot(1,3,1);
    showmesh(node, elem,opt_mesh);
    hold on;
    showmesh(node, elem(marked),opt_mark);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    axis off

    % refine
    [node, elem] = PolyMeshRefine(node, elem, marked);

    % display refined mesh with element numbering
    subplot(1,3,2);
    showmesh(node, elem, opt_mesh);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    axis off;

    % display refined mesh with node numbering
    subplot(1,3,3);
    showmesh(node, elem, opt_mesh);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    text(node(:,1), node(:,2), num2str((1:size(node,1)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on');
    axis off;
    drawnow;
end
```

![image](https://user-images.githubusercontent.com/17425440/115549888-29a73800-a2e4-11eb-83cc-01952012f642.png)
click the above figure for clear view.

I found that this bug can be made if the following holds:
1. E1 is marked and a neighboring element E2 is not marked.
2. E1 is divided into e1, e2, ..., en where e1, e2 are neighbor of E2.
3. e1, e2, E2 are marked

As e1, e2 are further refined, E2 should contain hanging nodes created from e1 and e2.
However, the hanging nodes from e1 and e2 are omitted from the refined polygons from E2.

I think the omitted nodes are the source of bug.
As there is omitted nodes, there could be repeated nodes (omitted node from one side will be duplicated)
and the detection of a midpoint fails.

This bug can be fixed by checking whether a neighboring element is further refined or not.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Terenceyuyue/mVEM/issues/1

**Comment by Terenceyuyue** [comment] 2021-04-22 09:28
Hi, Dohyun

  I have updated the M file PolyMeshRefine.m. 

  You can check whether the bug is resolved.

  Thank you !




----- 原始邮件 -----
发件人: "Dohyun Kim" ***@***.***>
收件人: "Terenceyuyue/mVEM" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期三, 2021年 4 月 21日 下午 8:06:14
主题: [Terenceyuyue/mVEM] two-level hanging node is not treated as expected (#1)

Hi!
I'm Dohyun, a postdoc working on staggered DG methods which also consider polygonal mesh.
I found [this arxiv manuscript](https://arxiv.org/pdf/2101.03456.pdf) and tried it myself.

I found that the code `PolyMeshRefine` contains two bugs
1) violate the one-hanging-node rule
2) non-unique node

The bug is reproducible by the following code

```MATLAB
% load sample mesh
load meshdata1.mat
% for consistent result
rng(0);
% display option
opt_mesh = struct('facecolor','none');
opt_mark = struct('facecolor','r');

toBeMarked = {[7], [9, 19, 20], [36]};
for i = 1 : 3
    marked = toBeMarked{i};
    % display current mesh and marked elements with node numbering
    figure;
    subplot(1,3,1);
    showmesh(node, elem,opt_mesh);
    hold on;
    showmesh(node, elem(marked),opt_mark);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    axis off

    % refine
    [node, elem] = PolyMeshRefine(node, elem, marked);

    % display refined mesh with element numbering
    subplot(1,3,2);
    showmesh(node, elem, opt_mesh);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    axis off;

    % display refined mesh with node numbering
    subplot(1,3,3);
    showmesh(node, elem, opt_mesh);
    text(cellfun(@(v) mean(node(v,1)), elem).', cellfun(@(v) mean(node(v,2)), elem).', num2str((1:length(elem)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on')
    text(node(:,1), node(:,2), num2str((1:size(node,1)).'), 'VerticalAlignment', 'middle', 'HorizontalAlignment', 'center', 'Clipping', 'on');
    axis off;
    drawnow;
end
```

![image](https://user-images.githubusercontent.com/17425440/115549888-29a73800-a2e4-11eb-83cc-01952012f642.png)
click the above figure for clear view.

I found that this bug can be made if the following holds:
1. E1 is marked and a neighboring element E2 is not marked.
2. E1 is divided into e1, e2, ..., en where e1, e2 are neighbor of E2.
3. e1, e2, E2 are marked

As e1, e2 are further refined, E2 should contain hanging nodes created from e1 and e2.
However, the hanging nodes from e1 and e2 are omitted from the refined polygons from E2.

I think the omitted nodes are the source of bug.
As there is omitted nodes, there could be repeated nodes (omitted node from one side will be duplicated)
and the detection of a midpoint fails.

This bug can be fixed by checking whether a neighboring element is further refined or not.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Terenceyuyue/mVEM/issues/1

**Comment by dohyun-cse** [comment] 2021-04-22 13:06
Hi Yu!

Thank you for the update.

I made another version of PolyMeshRefine.
Please revise the pull request.
Hope this does not offend you.

**Comment by Terenceyuyue** [comment] 2021-04-22 14:11
It's great!  I shall revise the pull request next week. Thank you once again!
By the way, I'm a PhD in SJTU in China.

**Comment by Terenceyuyue** [comment] 2021-04-25 15:27
Hi, Dohyun. 
Your version has been added in mVEM. Thank you for sharing your great idea.
I also revised the my PolyMeshRefine. The additional computational cost  is resulted from  the use of intersect.
Now both implementations are comparable.
Thank you once again!

**Closed as completed** 2021-05-25 10:49 UTC
